### ISSUE TITLE
How use this image with SWIFT v2.0 authorization?

### ISSUE THREAD

**Issue by Slach** [stmuraka/SAIO#1]
Could you explain what config i need change for replace proxy listen from 127.0.0.1 to 0.0.0.0 ?
Also what authorization credentials i need use for test v2.0 or how i can create swift users inside container?

**Comment by stmuraka** [comment]
@Slach the bind address from inside the container? you can change that in the `/etc/swift/proxy-server.conf`. However, you shouldn't need to do this as the host IP/port mapping you specify when you run the container should map to the container specified IP/port. More proxy-server.conf configuration can be found here: [https://docs.openstack.org/mitaka/config-reference/object-storage/proxy-server.html](https://docs.openstack.org/mitaka/config-reference/object-storage/proxy-server.html)

Test user credentials can be modified in the [test.conf](https://github.com/stmuraka/SAIO/blob/master/test.conf) file

**Comment by Slach** [comment]
Hi Thanks for your answer
Could you help me? 

I try create test staging confgiruation over docker-compose for  my wal-e backup script testing with SWIFT storage

i search proxy-sever.conf example whitch will correcly work with v2.0 authrorization protocol
i see https://docs.openstack.org/mitaka/config-reference/object-storage/proxy-server.html but don't fully understand what i need doing 

For v2.0 authorization protocol what is "keystonehost" ? Is keystone installed in your SAIO image?

**Comment by Slach** [comment]
@stmuraka hello again
could you help me?
swift SAIO container started OK

but when i try using following command
```
swift --auth-version 2 --os-auth-url http://swift.serv:8080/v2.0 --os-tenant-name test --os-username tester --os-password testing list --lh db-backup
```
i receive  error
```
Authorization Failure. Authorization Failed: Bad Request (HTTP 400) (Request-ID: txe09ea44fb6a94553ad3ab-005a3a5069)
```
and errors in docker stderr logs
```
swift-server_1    | Dec 20 11:58:33 d103a9a257be proxy-server: STDERR: 172.18.0.3 - - [20/Dec/2017 11:58:33] "POST /v2.0/tokens HTTP/1.1" 400 395 0.002308 (txn: txe09ea44fb6a94553ad3ab-005a3a5069)
```

i try use following proxy-server.conf
```
[DEFAULT]
bind_ip = 0.0.0.0
bind_port = 8080
workers = 1
user = swift
log_facility = LOG_LOCAL1
eventlet_debug = true

[pipeline:main]
# Yes, proxy-logging appears twice. This is so that
# middleware-originated requests get logged too.
pipeline = catch_errors gatekeeper healthcheck proxy-logging cache bulk tempurl ratelimit crossdomain container_sync tempauth staticweb copy container-quotas account-quotas slo dlo versioned_writes proxy-logging proxy-server

[filter:catch_errors]
use = egg:swift#catch_errors

[filter:healthcheck]
use = egg:swift#healthcheck

[filter:proxy-logging]
use = egg:swift#proxy_logging

[filter:bulk]
use = egg:swift#bulk

[filter:ratelimit]
use = egg:swift#ratelimit

[filter:crossdomain]
use = egg:swift#crossdomain

[filter:dlo]
use = egg:swift#dlo

[filter:slo]
use = egg:swift#slo

[filter:container_sync]
use = egg:swift#container_sync
current = //saio/saio_endpoint

[filter:tempurl]
use = egg:swift#tempurl

[filter:tempauth]
use = egg:swift#tempauth
user_admin_admin = admin .admin .reseller_admin
user_test_tester = testing .admin
user_test2_tester2 = testing2 .admin
user_test_tester3 = testing3

[filter:staticweb]
use = egg:swift#staticweb

[filter:account-quotas]
use = egg:swift#account_quotas

[filter:container-quotas]
use = egg:swift#container_quotas

[filter:cache]
use = egg:swift#memcache

[filter:gatekeeper]
use = egg:swift#gatekeeper

[filter:versioned_writes]
use = egg:swift#versioned_writes
allow_versioned_writes = true

[filter:copy]
use = egg:swift#copy

[app:proxy-server]
use = egg:swift#proxy
allow_account_management = true
account_autocreate = true
```


how i can solve my problem?

**Comment by memorais** [comment]
AFAIK you don't need keystone to use v2 auth in SAIO scenario [1]. You can use TempAuth in order to do that as well [2].

Remember you can't use TempAuth for production environments.

[1] - https://docs.openstack.org/swift/latest/development_saio.html
[2] - https://docs.openstack.org/swift/latest/overview_auth.html#tempauth

**Comment by Slach** [comment]
@memorais OK, i understand i don't need keystone, it's a good news

but what cretentials i need use to accept my SAIO swift server under docker-container?

currently i see following errors in docker-compose logs swift-server 
```
swift-server_1    | ---------------------------------------------------
swift-server_1    | Swift SAIO ready
swift-server_1    | Initialization time took: 0:00:29
swift-server_1    | ---------------------------------------------------
swift-server_1    |
swift-server_1    | ---------------------------------------------------
swift-server_1    | Tailing logs...
swift-server_1    | ---------------------------------------------------
swift-server_1    | ==> /var/log/swift/proxy.error <==

...
swift-server_1    | Jan 25 07:58:17 5156d92ac4f0 proxy-server: STDERR: 172.18.0.4 - - [25/Jan/2018 07:58:17] "POST /v2.0/tokens HTTP/1.1" 400 395 0.002822 (txn:
 tx91ccac3d18394787919ea-005a698e19)
```

when try use following commands
```
root@local-backup-manager-develop:/vagrant# swift --auth-version 1 --os-auth-url http://127.0.0.1:8080/auth --os-tenant-name admin --os-username admin --os-pas
sword admin list --lh -p /
```
swift-proxy-server working fine
````
root@local-backup-manager-develop:/vagrant# docker-compose exec swift-server ss -nltp | grep 8080
LISTEN     0      128          *:8080                     *:*                   users:(("swift-proxy-ser",pid=568,fd=4),("swift-proxy-ser",pid=397,fd=4))
```

**Comment by stmuraka** [comment]
@Slach if you're trying to use the swift CLI, try:
`swift -A http://127.0.0.1:8080/auth/v1.0 -U test:tester -K testing stat -v`

per the swift cli help:
```
  -A=AUTH, --auth=AUTH  URL for obtaining an auth token.
  -V=AUTH_VERSION, --auth-version=AUTH_VERSION, --os-identity-api-version=AUTH_VERSION
                        Specify a version for authentication. Defaults to
  -U=USER, --user=USER  User name for obtaining an auth token.
  -K=KEY, --key=KEY     Key for obtaining an auth token.
```
some references:

 - [https://docs.openstack.org/python-swiftclient/ocata/cli.html#legacy-auth-systems](https://docs.openstack.org/python-swiftclient/ocata/cli.html#legacy-auth-systems)
 - [https://docs.openstack.org/swift/latest/middleware.html#module-swift.common.middleware.tempauth](https://docs.openstack.org/swift/latest/middleware.html#module-swift.common.middleware.tempauth)
