### ISSUE TITLE
Impossible to access from outside container

### ISSUE THREAD

**Issue by memorais** [stmuraka/SAIO#2]
I'm trying do execute an "curl" from outside container but I'm getting the following error:

$ curl -v -H 'X-Storage-User: test:tester' -H 'X-Storage-Pass: testing' http://127.0.0.1:8080/auth/v1.0
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /auth/v1.0 HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.51.0
> Accept: */*
> X-Storage-User: test:tester
> X-Storage-Pass: testing
> 
* Recv failure: Connection reset by peer
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

If I run from inside container it runs perfectly:

$ docker exec saio curl -v -H 'X-Storage-User: test:tester' -H 'X-Storage-Pass: testing' http://127.0.0.1:8080/auth/v1.0
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /auth/v1.0 HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.47.0
> Accept: */*
> X-Storage-User: test:tester
> X-Storage-Pass: testing
> 
< HTTP/1.1 200 OK
< X-Storage-Url: http://127.0.0.1:8080/v1/AUTH_test
< X-Auth-Token-Expires: 85888
< X-Auth-Token: AUTH_tk1c27fd1b6d79400c930dbfc6de2f0211
< Content-Type: text/html; charset=UTF-8
< X-Storage-Token: AUTH_tk1c27fd1b6d79400c930dbfc6de2f0211
< Content-Length: 0
< X-Trans-Id: tx1fc4a890352e422d8bd42-005a67b164
< X-Openstack-Request-Id: tx1fc4a890352e422d8bd42-005a67b164
< Date: Tue, 23 Jan 2018 22:04:20 GMT
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host 127.0.0.1 left intact

Do you know whats going on? Here is how I run this container:

$ docker run -dP --name saio --privileged=true --volume saio_vol:/srv -e SKIP_TESTS=true -p 8080:8080 stmuraka/saio

Thanks.

**Comment by stmuraka** [comment]
@memorais looks like they changed the forwarding policy in Docker to not foward to IP/ports listening on the loopback (127.0.0.1) in the container.

I did a quick test and updated `bind_ip = 0.0.0.0` in `/etc/swift/proxy-server.conf` in the container and restarted the service (`~/bin/resetswift; ~/bin/startall`). That resulted in the following [running in the container]:
`tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1227/python`

[outside the container]
```
curl -v -H 'X-Storage-User: test:tester' -H 'X-Storage-Pass: testing' http://127.0.0.1:8080/auth/v1.0
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /auth/v1.0 HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.47.0
> Accept: */*
> X-Storage-User: test:tester
> X-Storage-Pass: testing
>
< HTTP/1.1 200 OK
< X-Storage-Url: http://127.0.0.1:8080/v1/AUTH_test
< X-Auth-Token-Expires: 86399
< X-Auth-Token: AUTH_tked68e0b43cc347899cb0674cd6104085
< Content-Type: text/html; charset=UTF-8
< X-Storage-Token: AUTH_tked68e0b43cc347899cb0674cd6104085
< Content-Length: 0
< X-Trans-Id: tx04bf54c6b4674176a9ebd-005a68b3cb
< X-Openstack-Request-Id: tx04bf54c6b4674176a9ebd-005a68b3cb
< Date: Wed, 24 Jan 2018 16:26:51 GMT
<
* Connection #0 to host 127.0.0.1 left intact
```
 I can push a change later in the week, but you should be able to get by with that for now

**Comment by memorais** [comment]
Yes, I did and it work.

Thanks!

**Comment by Slach** [comment]
Guys ;) how i can use this credentials 
```
user=test:tester  password=testing 
```

with v2.0 authorization? ;)
could anybody get me right  curl request ? or swift cli parameters example?

and yes, my proxy-server.conf have 
bind_ip = 0.0.0.0

**Comment by stmuraka** [comment]
Made update. Docker build triggered in docker hub.
